import type { Metadata } from "next";




import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});



export const metadata: Metadata = {
  title: "Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}  font-montserrat bg-red-50 w-full min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
